/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1ztOjIUO9hp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"
export function LogIn() {
  return (
    <Card className="w-[400px]">
      <CardHeader className="flex flex-row justify-center">
        <Image  src="/favicon.ico" width={72} height={50} alt="Logo DiU" />
      </CardHeader>
      <CardContent className="px-7">
        <section className="my-3 -mt-5">
          <article className="space-y-2 my-2">
            <Label className="block text-sm leading-6 text-gray-900 font-semibold">Email</Label>
            <Input 
            className="rounded-xl border"
            id="email"
            name="email"
            placeholder="Ingrese su email"
            required
            type="email"
            />
          </article>
          <article className="space-y-2 my-2">
            <Label className="block text-sm leading-6 text-gray-900 font-semibold">Contraseña</Label>
            <Input 
            className="rounded-xl border"
            id="email"
            name="email"
            placeholder="Ingrese su email"
            required
            type="password"
            />
          </article>
          <article className="flex justify-center w-full mt-5">
              <Button
                variant="secondary"
                type='submit'
                className="w-full rounded-2xl bg-custom-blue px-3 py-2 text-sm font-semi bold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                Continuar
              </Button>

          </article>
          <article className="flex justify-center items-center">
            <Link className="text-sm p-4" href="/signup">
              No tienes cuenta? Registrate
            </Link>
          </article>
        </section>
      </CardContent>

    </Card>
  )
}
