/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1ztOjIUO9hp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"
export function LogIn() {
  return (
    <Card className="w-96 px-10 py-3">
      <CardHeader className="flex flex-row justify-between">
        <Image className="bg-custom-blue" src="/logo-du.png" width={72} height={50} alt="Logo DiU"/>
        <CardTitle className="text-4xl text-center font-black">DOWN IS UP</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label className="text-xl" htmlFor="username">Usuario</Label>
          <Input id="username" placeholder="Ingrese su usuario" required type="text" />
        </div>
        <div className="space-y-2">
          <Label className="text-xl" htmlFor="password">Contraseña</Label>
          <Input id="password" className="" placeholder="Ingrese su contraseña"  required type="password"/>
        </div>
      </CardContent>
      <CardFooter>
        <Button className="w-full hover:bg-blue-500 transition-colors text-xl">Ingresar</Button>
      <Link href="/signup" className="text-center text-sm">
        ¿No tienes cuenta? Crear una cuenta
      </Link>
      </CardFooter>
    </Card>
  )
}
