classDiagram
    Usuario <|-- Paciente: hereda
    Usuario <|-- Administrador: hereda
    Usuario <|-- Especialista: hereda
    Turno <-- Estado: tiene 
    Paciente <-- fichaMedica: tiene 
    Paciente <-- HistoriaClinica: tiene
    Paciente <-- Turno: tiene 

    class Usuario {
        -String nombre
        -String apellido
        -String correo
        -String contraseña
        -Int telefono
        -String direccion
        -String ciudad
        -String pais
        -Date fechaNacimiento
        
        +getNombreCompleto(): String
        +setNombre(nombre: String): void
        +setApellido(apellido: String): void
        +setCorreo(correo: String): void
        +setContraseña(contraseña: String): void
        +setTelefono(telefono: Int): void
        +setDireccion(direccion: String): void
        +setCiudad(ciudad: String): void
        +setPais(pais: String): void
        +setFechaNacimiento(fechaNacimiento: Date): void
    }


    class Turno {
        -Date fecha
        -Time hora
        -String especialista
        -String paciente
        -Estado estado

        +getFecha(): Date
        +setFecha(fecha: Date): void
        +getHora(): Time
        +setHora(hora: Time): void
        +getEspecialista(): String
        +setEspecialista(especialista: String): void
        +getPaciente(): String
        +setPaciente(paciente: String): void
        +getEstado(): Estado
        +setEstado(estado: Estado): void
    }

    class Estado {
        -String estado
        -String descripcion
    }

    class Paciente {
        -String nombre
        -String apellido
        -Int dni

        +getNombre(): String
        +setNombre(nombre: String): void
        +setApellido(apellido: String): void
        +setDni(dni: Int): void
    }

    class Especialista {
        -String nombre
        -String apellido
        -String especialidad

        +getNombre(): String
        +setNombre(nombre: String): void
        +setApellido(apellido: String): void
        +setEspecialidad(especialidad: String): void
    }


    class Administrador {
        -String nombre
        -String apellido
        -String correo
        -String contraseña
        -Int telefono
        -String direccion
        -String ciudad
        -String pais
        -Date fechaNacimiento

        +getNombreCompleto(): String
        +setNombre(nombre: String): void
        +setApellido(apellido: String): void
        +setCorreo(correo: String): void
        +setContraseña(contraseña: String): void
        +setTelefono(telefono: Int): void
        +setDireccion(direccion: String): void
        +setCiudad(ciudad: String): void
        +setPais(pais: String): void
        +setFechaNacimiento(fechaNacimiento: Date): void
    }

    class fichaMedica {
        -Paciente paciente
        -Especialista especialista
        -Date fecha
        -String motivoConsulta
        -String antecedentes
        -String examenFisico
        -String diagnostico
        -String observaciones

        +getPaciente(): Paciente
        +setPaciente(paciente: Paciente): void
        +getEspecialista(): Especialista
        +setEspecialista(especialista: Especialista): void
        +getFecha(): Date
        +setFecha(fecha: Date): void
        +getMotivoConsulta(): String
        +setMotivoConsulta(motivoConsulta: String): void
        +getAntecedentes(): String
        +setAntecedentes(antecedentes: String): void
        +getExamenFisico(): String
        +setExamenFisico(examenFisico: String): void
        +getDiagnostico(): String
        +setDiagnostico(diagnostico: String): void
        +getObservaciones(): String
        +setObservaciones(observaciones: String): void
    }

    class HistoriaClinica {
        -Paciente paciente
        -Especialista especialista
        -Date fecha
        -String antecedentes
        -String examenFisico
        -String diagnostico
        -String observaciones

        +getPaciente(): Paciente
        +setPaciente(paciente: Paciente): void
        +getEspecialista(): Especialista
        +setEspecialista(especialista: Especialista): void
        +getFecha(): Date
        +setFecha(fecha: Date): void
        +getAntecedentes(): String
        +setAntecedentes(antecedentes: String): void
        +getExamenFisico(): String
        +setExamenFisico(examenFisico: String): void
        +getDiagnostico(): String
        +setDiagnostico(diagnostico: String): void
        +getObservaciones(): String
        +setObservaciones(observaciones: String): void
    }
