erDiagram

    Usuario {
        int idUsuario PK
        varchar nombre
        varchar apellido
        varchar email
        varchar contrasenia
        varchar telefono
        date fechaNacimiento
        int idTipoUsuario FK
        int idDireccion FK
    }
    
    TipoUsuario {
        int idTipoUsuario PK
        varchar nombre
        text descripcion
    }

    Especialista {
        int matricula PK
        int idUsuario FK
        int idEspecialidad FK

    }
    
    Especialidad {
        int idEspecialidad PK
        varchar nombre
        text descripcion
    }
    
    Turno {
        int idTurno PK
        int matriculaEspecialista FK
        date fecha
        time horaInicioReal
        time horaFinReal
        time horaInicioEstimada
        time horaFinEstimada
        int idEstadoTurno FK
    }

    EstadoTurno {
        int idEstadoTurno PK
        varchar nombre
        text descripcion
    }

    FichaPaciente {
        int idFichaPaciente PK
        int idUsuario FK
        float altura
        float peso
        int idObraSocial FK
        int idGrupoSanguineo FK
        int idAntecedentePrevio FK
        
    }

    AntecedentePrevio {
        int idAntecedentePrevio PK
        int idFichaPaciente FK
        varchar nombre
        text descripcion
        date fecha
    }
    GrupoSanguineo {
        int idGrupoSanguineo PK
        varchar Factor
        varchar Grupo

    }
    ObraSocial {
        int idObraSocial PK
        varchar nombre
        text descripcion
    }
    Direccion {
        int idDireccion PK
        varchar calle
        varchar numero
        varchar codigoPostal
        int idCiudad
    }

    Ciudad {
        int idCiudad PK
        varchar nombre
        int idProvincia FK
    }

    Provincia {
        int idProvincia PK
        varchar nombre
        int idPais FK
    }

    Pais {
        int idPais PK
        varchar nombre
    }
